import { useRouter } from "next/router"
import Head from 'next/head'
import styles from '../../styles/Home.module.css'

const Berita = () => {
  const router = useRouter();

  const { query } = router;
  return (
    <div className={styles.main}>
      <Head>
        <title>{query.title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h3>Berita Hari ini</h3>
      <p>judul: {query.title}</p>
      <p>isi: {query.content}</p>
    </div>
  )
}

export default Berita