import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import ssImg from '../assets/ss.png'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.navwrapper}>
        <h3 className='none'>beritaagakngawur.com</h3>
        <nav>
          <Link 
            href='/books'
          >
            <a className={styles.navmenu}>Books</a>
          </Link>
          <Link 
            href='/news'
          >
            <a className={styles.navmenu}>News</a>
          </Link>
          <Link 
            href={{pathname:'/about', query:{name:'fahmi',address:'ngawi'}}}
            as='/about-fahmi'
          >
            <a className={styles.navmenu}>About me</a>
          </Link>
        </nav>
      </div>

      <main className={styles.main}>
        <p>Selamat data di situs beritaagakngawur.com</p>
        <p>show image with html tag</p>
        <img src="/beach.png" alt="" width={200} height={200}/>
        <p>show next/image public folder</p>
        <Image src="/beach.png" alt="" width={200} height={200}/>
        <p>show next/image another folder</p>
        <Image src={ssImg} alt="" width={200} height={200}/>
        <p>show next/image outside image</p>
        <Image 
          src="https://images.unsplash.com/photo-1598128558393-70ff21433be0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=489&q=80"
          alt="" width={200}
          height={200}
        />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
